
name: Release Branch Created

# Run whenever a ref is created https://docs.github.com/en/actions/reference/events-that-trigger-workflows#create
on:
  create

jobs:
  # First job in the workflow builds and verifies the software artifacts
  bump:
    name: Bump minor version on develop
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Only run if ref created was a release branch
    if:
      ${{ startsWith(github.ref, 'refs/heads/release/') }}
    steps:
      # Checks-out the develop branch
      - uses: actions/checkout@v4
        with:
          ref: 'refs/heads/develop'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.3.2
      - name: Bump minor version
        env:
          COMMIT_VERSION: ${{ github.ref }}
        run: |

          # only update the develop branch if were making #.#.0 release
          # Get the branch name from the GITHUB_REF environment variable
          branch_name=${GITHUB_REF#refs/heads/}

          # Extract the last number in the branch name using a regular expression
          if [[ $branch_name =~ /([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then

            first_number=${BASH_REMATCH[1]}
            middle_number=${BASH_REMATCH[2]}
            last_number=${BASH_REMATCH[3]}

            # Increment the middle number by 1
            incremented_middle_number=$((middle_number + 1))

            # Check if the last number is '0'
            if [ "$last_number" == "0" ]; then

              update_version=$first_number.$incremented_middle_number.$last_number-alpha.1

              poetry version $update_version
              echo "software_version=$update_version" >> $GITHUB_ENV

              git config --global user.name 'podaac-tig bot'
              git config --global user.email 'podaac-tig@noreply.github.com'
              git commit -am "/version ${{ env.software_version }}"
              git push

            fi

          fi